# Generated by Django 5.0 on 2023-12-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_book_publiction_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('city_persain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('Gender_person', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('role_persain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=100)),
                ('semester_persain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contant_no', models.IntegerField(max_length=100)),
                ('identification_no', models.IntegerField(max_length=100)),
                ('Registration_no', models.IntegerField(max_length=100)),
                ('page_no', models.IntegerField(max_length=100)),
                ('original_Address', models.CharField(max_length=100)),
                ('current_Address', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Is_Active', models.SmallIntegerField()),
                ('signature', models.CharField(max_length=100)),
                ('feculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.faculty')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Despositves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('Copy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.copy')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customusers')),
            ],
        ),
    ]
